spring:
  mail:
    host: smtp.gmail.com
    port: ${GOOGLE_SMTP_PORT:8080}
    username: ${GOOGLE_SMTP_USERNAME:test}
    password: ${GOOGLE_SMTP_PASSWORD:test}

---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: ${LOCAL_REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

---

spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${DEV_REDIS_HOST}
    port: ${REDIS_PORT}

---

spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: ${PROD_REDIS_HOST}
    port: ${REDIS_PORT}