aws:
  ses:
    access-key: ${SES_ACCESS_KEY}
    secret-key: ${SES_SECRET_KEY}
    region : ${SES_REGION}

---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: ${LOCAL_REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

---

spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${DEV_REDIS_HOST}
    port: ${REDIS_PORT}

---

spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: ${PROD_REDIS_HOST}
    port: ${REDIS_PORT}